using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace AnimeLocalTracker.Services;

/// <summary>
/// Localización ES/EN con cambio en caliente: las vistas enlazan con
/// {Binding [Clave], Source={x:Static loc:LocalizationService.Instance}} y al
/// cambiar Idioma se eleva PropertyChanged("Item[]") → todos los textos se
/// refrescan al instante sin reiniciar. Las cadenas generadas en código usan T().
/// </summary>
public sealed class LocalizationService : INotifyPropertyChanged
{
    public static LocalizationService Instance { get; } = new();

    private string _idioma = "es";
    public string Idioma
    {
        get => _idioma;
        set
        {
            // LOC-03: normalizar — cualquier valor que no sea "en" se trata como "es"
            value = value == "en" ? "en" : "es";
            if (_idioma != value)
            {
                _idioma = value;
                OnPropertyChanged("Item[]");
            }
        }
    }

    private static readonly Dictionary<string, string> Es = new()
    {
        ["Nav_Galeria"] = "Galería",
        ["Nav_Historial"] = "Historial",
        ["Nav_Actualizaciones"] = "Actualizaciones",
        ["Nav_Agregar"] = "Agregar Anime",
        ["Nav_Calendario"] = "Calendario",
        ["Nav_Descargas"] = "Descargas",
        ["Nav_Configuracion"] = "Configuración",
        ["Nav_AcercaDe"] = "Acerca de",

        ["Cfg_Almacenamiento"] = "Almacenamiento",
        ["Cfg_AlmacenamientoSub"] = "Carpeta donde se guardan y organizan tus animes",
        ["Cfg_RutaHint"] = "Ruta de Almacenamiento",
        ["Cfg_CambiarCarpeta"] = "Cambiar Carpeta",
        ["Cfg_Explorador"] = "Explorador",
        ["Cfg_EspacioDisco"] = "Espacio en Disco",
        ["Cfg_TotalAnimes"] = "animes registrados",
        ["Cfg_LimpiarCache"] = "Limpiar caché de imágenes",
        ["Cfg_LimpiarCacheTip"] = "Elimina miniaturas y portadas de animes que ya no existen en tu biblioteca",
        ["Cfg_ExportarBackup"] = "Exportar copia de seguridad de la base de datos",
        ["Cfg_BackupOk"] = "Copia de seguridad creada correctamente.",
        ["Cfg_BackupError"] = "No se pudo crear la copia de seguridad.",
        ["Cfg_ExportarBiblioteca"] = "Exportar biblioteca (JSON)",
        ["Cfg_BibliotecaExportada"] = "Biblioteca exportada: {0} animes y su historial.",
        ["Cfg_ImportarBiblioteca"] = "Importar biblioteca (JSON)",
        ["Cfg_ImportarConfirmacion"] = "Se fusionará la biblioteca del archivo con la actual (los animes existentes se actualizarán). ¿Continuar?",
        ["Cfg_BibliotecaImportada"] = "Biblioteca importada: {0} animes fusionados.",
        ["Cfg_BtnBackup"] = "Exportar copia de seguridad",
        ["Cfg_BtnExportarJson"] = "Exportar biblioteca (JSON)",
        ["Cfg_BtnImportarJson"] = "Importar biblioteca (JSON)",

        ["Cfg_Reproduccion"] = "Reproducción y Descargas",
        ["Cfg_ReproduccionSub"] = "Ajustes de comportamiento del reproductor y concurrencia",
        ["Cfg_AutoPlay"] = "Auto-Play del siguiente episodio",
        ["Cfg_AutoPlaySub"] = "Muestra cuenta regresiva de 5s y reproduce automáticamente el siguiente capítulo",
        ["Cfg_AutoSkip"] = "Saltar Intro / Outro automáticamente (AniSkip)",
        ["Cfg_AutoSkipSub"] = "Omite openings y endings de forma automática sin necesidad de hacer clic",
        ["Cfg_Subtitulos"] = "Subtítulos activados por defecto",
        ["Cfg_SubtitulosSub"] = "Carga pistas de subtítulos automáticamente al iniciar un video",
        ["Cfg_DescargasSimultaneas"] = "Descargas simultáneas máximas",
        ["Cfg_DescargasSimultaneasSub"] = "Cantidad de episodios descargándose en paralelo (1 a 5)",
        ["Cfg_IntervaloSync"] = "Intervalo de sincronización con AniList",
        ["Cfg_IntervaloSyncSub"] = "Frecuencia en segundo plano para sincronizar el historial de visualización",
        ["Cfg_Velocidad"] = "Velocidad de reproducción por defecto",
        ["Cfg_VelocidadSub"] = "Se aplica al abrir cada episodio (ajustable en el reproductor)",
        ["Cfg_Atajos"] = "Atajos de teclado del reproductor",
        ["Cfg_AtajosSub"] = "Personaliza las teclas rápidas (se aplican al abrir el reproductor)",
        ["Atajo_PlayPausa"] = "Reproducir / Pausar",
        ["Atajo_PantallaCompleta"] = "Pantalla completa",
        ["Atajo_Silenciar"] = "Silenciar",
        ["Atajo_SubirVolumen"] = "Subir volumen",
        ["Atajo_BajarVolumen"] = "Bajar volumen",
        ["Atajo_Adelantar10"] = "Adelantar 10 s",
        ["Atajo_Retroceder10"] = "Retroceder 10 s",
        ["Atajo_SaltarIntro"] = "Saltar intro/outro",
        ["Atajo_SiguienteEpisodio"] = "Siguiente episodio",
        ["Atajo_AnteriorEpisodio"] = "Episodio anterior",
        ["Atajo_Cerrar"] = "Cerrar reproductor",
        ["Atajo_CapturarFrame"] = "Capturar frame (screenshot)",
        ["Cfg_UmbralVisto"] = "Umbral para marcar como visto",
        ["Cfg_UmbralVistoSub"] = "Porcentaje reproducido del episodio a partir del cual se marca automáticamente como visto",
        ["Cfg_NotificarEpisodios"] = "Notificar episodios nuevos",
        ["Cfg_NotificarEpisodiosSub"] = "Avisa cuando aparecen archivos de episodios nuevos en tu biblioteca",
        ["Cfg_Idioma"] = "Idioma / Language",
        ["Cfg_IdiomaSub"] = "El cambio se aplica al instante",
        ["Cfg_Guardar"] = "Guardar Preferencias",

        ["Cfg_Cuenta"] = "Cuenta AniList y Sincronización",
        ["Cfg_CuentaSub"] = "Estado de enlace para sincronizar progreso con tu perfil en la nube",
        ["Cfg_SyncSub"] = "Los episodios marcados como vistos se sincronizan automáticamente con tu perfil online de AniList",
        ["Cfg_CerrarSesion"] = "Cerrar Sesión",

        ["Notif_NuevosEpisodios"] = "Episodios nuevos",
        ["Notif_ResumenNuevos"] = "nuevo(s) episodio(s) detectado(s) en tu biblioteca:",
        ["Notif_SinTitulo"] = "Anime",

        // === ESTADÍSTICAS (LOC-01) ===
        ["Stats_Titulo"] = "Panel de Estadísticas",
        ["Stats_Subtitulo"] = "Análisis de tu historial de visualización",
        ["Stats_EpisodiosVistos"] = "EPISODIOS VISTOS",
        ["Stats_HorasReproducidas"] = "HORAS REPRODUCIDAS",
        ["Stats_AnimesBiblioteca"] = "ANIMES EN BIBLIOTECA",
        ["Stats_BibliotecaCompletada"] = "BIBLIOTECA COMPLETADA",
        ["Stats_AMedioVer"] = "A medio ver",
        ["Stats_EpisodiosFavoritos"] = "Episodios favoritos",
        ["Stats_EpisodiosDescargados"] = "Episodios descargados",
        ["Stats_DuracionPromedio"] = "Duración promedio / ep.",
        ["Stats_GeneroFavorito"] = "GÉNERO FAVORITO",
        ["Stats_AnimeMasVisto"] = "ANIME MÁS VISTO",
        ["Stats_AnioMasActivo"] = "AÑO MÁS ACTIVO",
        ["Stats_Ritmo"] = "RITMO",
        ["Stats_PorMes"] = " / mes",
        ["Stats_RachaActual"] = "Racha actual: ",
        ["Stats_DistribucionLista"] = "Distribución de tu lista",
        ["Stats_PorEstado"] = "Por estado de seguimiento",
        ["Stats_DonutCentroAnimes"] = "animes",
        ["Stats_AnalisisGenero"] = "Análisis de género",
        ["Stats_GeneroSub"] = "Animes con episodios vistos, por género",
        ["Stats_Actividad7Dias"] = "Actividad de los últimos 7 días",
        ["Stats_PromedioDiarioSub"] = " episodios/día · racha máxima: ",
        ["Stats_TopAnimes"] = "Top 5 animes más vistos",
        ["Stats_TopAnimesSub"] = "Por número de episodios reproducidos",
        ["Stats_PorAnio"] = "Episodios vistos por año",
        ["Stats_PorAnioSub"] = "Evolución de tu consumo anual",

        // === VENTANA PRINCIPAL (LOC-01) ===
        ["Nav_Estadisticas"] = "Estadísticas",
        ["Nav_ComprobarUpdates"] = "Comprobar actualizaciones en GitHub",
        ["Nav_PantallaCompleta"] = "Pantalla Completa (F11)",
        ["Dlg_Cancelar"] = "CANCELAR",
        ["Dlg_Aceptar"] = "ACEPTAR",

        // === DIÁLOGOS (LOC-04) ===
        ["Dlg_NuevaVersion"] = "Nueva versión disponible",
        ["Dlg_EncontroVersion"] = "Se encontró la versión {0}. ¿Deseas descargarla e instalarla ahora?",
        ["Dlg_AnimeExistente"] = "Anime Existente",
        ["Dlg_AnimeExistenteMsj"] = "El anime '{0}' ya se encuentra en tu biblioteca.",
        ["Dlg_AnimeAnadido"] = "Anime Añadido",
        ["Dlg_AnimeAnadidoMsj"] = "Carpeta creada automáticamente en:\n{0}",
        ["Dlg_ErrorTitulo"] = "Error",
        ["Dlg_ErrorAnadirAnime"] = "No se pudo añadir el anime: {0}",
        ["Msg_NuevaVersion"] = "nueva versión",
        ["Dlg_UpdatesModoDevTitulo"] = "Actualizaciones",
        ["Dlg_UpdatesModoDev"] = "Estás en modo de desarrollo ({0}). Las actualizaciones automáticas se habilitan al compilar con el instalador de producción.",
        ["Dlg_UpdatesAlDiaTitulo"] = "Al día",
        ["Dlg_UpdatesAlDia"] = "Ya tienes la última versión instalada ({0}).",
        ["Dlg_UpdatesErrorConexionTitulo"] = "Error de conexión",
        ["Dlg_UpdatesErrorConexion"] = "No se pudo consultar el servidor de actualizaciones en GitHub. Comprueba tu conexión a internet.",
        ["Dlg_UpdatesListaTitulo"] = "Actualización lista",
        ["Dlg_UpdatesLista"] = "La versión {0} se ha descargado y está lista para aplicarse.",

        // === CONFIGURACIÓN (LOC-02) ===
        ["Cfg_CambiarCarpetaTip"] = "Elegir una nueva carpeta de almacenamiento",
        ["Cfg_ExploradorTip"] = "Abrir en el Explorador de Windows",
        ["Cfg_ColeccionTotal"] = "Colección Total",
        ["Tecla_Espacio"] = "Espacio",

        // === RESTAURAR BACKUP (BAK-03) ===
        ["Cfg_BtnRestaurar"] = "Restaurar copia",
        ["Cfg_RestaurarBackup"] = "Restaurar copia de seguridad",
        ["Cfg_RestaurarConfirmacion"] = "Se reemplazará la biblioteca actual por la copia seleccionada. ¿Continuar?",
        ["Cfg_RestaurarOk"] = "Biblioteca restaurada correctamente.",
        ["Cfg_RestaurarError"] = "No se pudo restaurar la copia (archivo inválido o corrupto).",

        // === HISTORIAL ===
        ["Hist_Titulo"] = "Historial de Reproducción",
        ["Hist_Subtitulo"] = "Tus episodios en curso y vistos recientemente",
        ["Hist_FiltroTodos"] = "Todos",
        ["Hist_FiltroEnProgreso"] = "En progreso",
        ["Hist_FiltroCompletados"] = "Completados",
        ["Hist_BuscarPlaceholder"] = "Buscar en el historial...",
        ["Hist_LimpiarHistorial"] = "Limpiar historial",
        ["Hist_LimpiarTitulo"] = "¿Vaciar todo el historial?",
        ["Hist_LimpiarMensaje"] = "Se restablecerá la fecha de reproducción y el progreso de todos los episodios. Tus archivos de video y tu biblioteca no se modificarán.",
        ["Hist_Reanudar"] = "Reanudar",
        ["Hist_VerAnime"] = "Ver detalles",
        ["Hist_Quitar"] = "Quitar del historial",
        ["Hist_MarcarVisto"] = "Marcar como visto",
        ["Hist_MarcarNoVisto"] = "Marcar como no visto",
        ["Hist_VacioTitulo"] = "Tu historial está vacío",
        ["Hist_VacioSubtitulo"] = "Los episodios que reproduzcas o dejes a medias aparecerán aquí automáticamente.",
        ["Hist_ExplorarGaleria"] = "Explorar biblioteca",
        ["Hist_SinResultados"] = "No se encontraron episodios que coincidan con la búsqueda.",
        ["Hist_ArchivoNoEncontrado"] = "El archivo de video ya no existe en la ruta registrada.",
        ["Hist_FechaHoy"] = "Hoy",
        ["Hist_FechaAyer"] = "Ayer",
        ["Hist_FechaSemana"] = "Esta semana",
        ["Hist_FechaMes"] = "Este mes",
        ["Hist_FechaAnteriores"] = "Anteriores",
        ["Hist_HaceMin"] = "Hace {0} min",
        ["Hist_NoEnBiblioteca"] = "'{0}' ya no está en tu biblioteca local. Añádelo desde la pestaña + para poder verlo o descargarlo.",

        // === ACTUALIZACIONES ===
        ["Act_Titulo"] = "Actualizaciones",
        ["Act_Subtitulo"] = "Capítulos recién emitidos de tus animes en emisión",
        ["Act_Descargar"] = "Descargar",
        ["Act_Reproducir"] = "Reproducir episodio",
        ["Act_Descargado"] = "Descargado",
        ["Act_EpisodioFormato"] = "Episodio {0}",
        ["Act_BotonActualizar"] = "ACTUALIZAR",
        ["Act_VerAnime"] = "Ver ficha del anime",
        ["Act_VacioTitulo"] = "Sin capítulos recientes",
        ["Act_VacioSub"] = "Aquí verás los capítulos recién emitidos en los últimos 7 días de los animes en emisión de tu biblioteca.",
        ["Act_HaceDias"] = "Hace {0} días",

        // === TÍTULO DE CONFIGURACIÓN (LOC-07) ===
        ["Cfg_Titulo"] = "Configuración y Preferencias",
        ["Cfg_TituloSub"] = "Personaliza el almacenamiento de tus animes, reproducción multimedia y sincronización con AniList",

        // === MODO PIP / MINI REPRODUCTOR ===
        ["Player_Pip"] = "Modo ventana flotante (P)",
        ["Player_Mini"] = "Minimizar a mini-reproductor (P)",
        ["Player_RestaurarFormato"] = "Restaurar formato habitual (P)",
        ["Player_Cerrar"] = "Cerrar reproductor",
        ["Player_RestaurarPip"] = "Restaurar reproductor",
        ["Pip_Banner_Reproduciendo"] = "Reproduciendo en ventana flotante:",

        // === GALERÍA ===
        ["Gal_Titulo"] = "Mi Colección",
        ["Gal_QueVerTip"] = "Elegir el siguiente episodio no visto de un anime al azar",
        ["Gal_QueVeoHoy"] = "QUÉ VEO HOY",
        ["Gal_Buscando"] = "BUSCANDO...",
        ["Gal_SeleccionMultiple"] = "Selección múltiple",
        ["Gal_ActualizarNube"] = "Actualizar datos desde la nube",
        ["Gal_ConectarTip"] = "Conectar con AniList",
        ["Gal_Conectar"] = "CONECTAR",
        ["Gal_CuentaSincronizadaTip"] = "Cuenta sincronizada con AniList (Clic para opciones)",
        ["Gal_BuscarHint"] = "Buscar anime guardado...",
        ["Gal_FiltrosTip"] = "Filtros por género, ordenación y más",
        ["Gal_Filtros"] = "Filtros",
        ["Gal_FiltroViendo"] = "Viendo",
        ["Gal_FiltroPlaneando"] = "Planeando",
        ["Gal_SoloPendientesTip"] = "Mostrar solo animes con episodios pendientes por ver",
        ["Gal_Pendientes"] = "Pendientes",
        ["Gal_SoloCarpetaTip"] = "Mostrar solo animes que tienen una carpeta de archivos asignada",
        ["Gal_ConCarpetaLocal"] = "Con carpeta local",
        ["Gal_LimpiarFiltrosTip"] = "Restablecer todos los filtros y búsqueda",
        ["Gal_LimpiarFiltros"] = "Limpiar filtros",
        ["Gal_MoverA"] = "Mover a:",
        ["Gal_Cancelar"] = "Cancelar",
        ["Gal_VacioTitulo"] = "Tu biblioteca está vacía",
        ["Gal_VacioSub"] = "Añade un anime para empezar tu colección local",
        ["Gal_BuscarYAnadir"] = "BUSCAR Y AÑADIR ANIME",
        ["Gal_SinResultadosTitulo"] = "No se encontraron animes",
        ["Gal_SinResultadosSub"] = "Intenta usar otros términos de búsqueda o cambia el filtro de estado.",
        ["Gal_NuevosEpisodiosFormato"] = "{0} Nuevos",

        // === DETALLE ===
        ["Det_EnBibliotecaTip"] = "En tu biblioteca (clic para eliminar)",
        ["Det_Biblioteca"] = "Biblioteca",
        ["Det_SeguimientoTip"] = "Gestionar seguimiento y progreso en AniList",
        ["Det_Seguimiento"] = "Seguimiento",
        ["Det_WebViewTip"] = "Abrir ficha oficial en el navegador web",
        ["Det_WebView"] = "WebView",
        ["Det_EpisodiosFormato"] = "{0} episodios",
        ["Det_OrdenTip"] = "Cambiar orden ascendente/descendente",
        ["Det_Carpeta"] = "Carpeta",
        ["Det_CarpetaTip"] = "Abrir la carpeta del anime en el Explorador",
        ["Det_DetectarOpTip"] = "Analizar audios con el plugin para detectar openings",
        ["Det_DetectarOp"] = "Detectar OP",
        ["Det_MarcarVistosTip"] = "Marcar episodios seleccionados (o todos) como vistos",
        ["Det_Vistos"] = "Vistos",
        ["Det_MarcarNoVistosTip"] = "Marcar episodios seleccionados (o todos) como no vistos",
        ["Det_NoVistos"] = "No vistos",
        ["Det_ActualizarTip"] = "Actualizar información y episodios desde AniList",
        ["Det_Actualizar"] = "Actualizar",
        ["Det_DuplicadosTip"] = "Detectar archivos duplicados por hash perceptual",
        ["Det_Duplicados"] = "Duplicados",
        ["Det_Analizando"] = "Analizando...",
        ["Det_EliminarEpisodio"] = "Eliminar episodio del disco",
        ["Det_FavoritoTip"] = "Marcar como favorito / guardado",
        ["Det_OpcionesTip"] = "Opciones (eliminar, etc.)",
        ["Det_OpcionesNombre"] = "Opciones de episodio descargado",
        ["Det_DescargandoTip"] = "Descargando episodio",
        ["Det_DescargarEpisodioTip"] = "Descargar episodio",
        ["Det_ReanudarTip"] = "Continuar reproduciendo el episodio en progreso",
        ["Det_ActualizarAniListTitulo"] = "Actualizar en AniList",
        ["Det_ActualizarAniListSub"] = "Sincroniza tu progreso y puntuación con la nube",
        ["Det_CerrarVentanaTip"] = "Cerrar ventana",
        ["Det_Estado"] = "Estado",
        ["Det_EpisodiosVistos"] = "Episodios Vistos",
        ["Det_Puntuacion"] = "Puntuación",
        ["Det_FechaInicio"] = "Fecha de Inicio",
        ["Det_FechaFin"] = "Fecha de Fin",
        ["Det_GuardarAniList"] = "Guardar en AniList",

        // === AGREGAR ANIME ===
        ["Add_Titulo"] = "Añadir Anime",
        ["Add_Subtitulo"] = "Explora tendencias o busca cualquier anime en AniList para tu colección local",
        ["Add_BuscarHint"] = "Buscar por título (ej. Frieren, Solo Leveling, Bleach)...",
        ["Add_LimpiarBusquedaTip"] = "Limpiar búsqueda",
        ["Add_Cargando"] = "Cargando animes desde AniList...",
        ["Add_SinResultadosTitulo"] = "No se encontraron resultados",
        ["Add_SinResultadosSub"] = "Prueba escribiendo el título en Romaji, inglés o con menos palabras clave.",
        ["Add_VerTendencias"] = "Ver tendencias populares",
        ["Add_AnadirBibliotecaTip"] = "Añadir a mi biblioteca local",
        ["Add_AnadirBiblioteca"] = "Añadir a biblioteca",
        ["Add_VerBibliotecaTip"] = "Ver detalles en tu biblioteca",
        ["Add_EnBiblioteca"] = "En tu biblioteca",

        // === REPRODUCTOR (tooltips) ===
        ["Player_VolverFicha"] = "Volver a la ficha del anime",
        ["Player_SaltarSegmento"] = "Saltar segmento (Atajo: S)",
        ["Player_ProgresoEpisodio"] = "Progreso del episodio",
        ["Player_PlayPausaTooltip"] = "Reproducir / Pausar (Espacio)",
        ["Player_SilenciarToggle"] = "Silenciar o reactivar sonido",
        ["Player_SilenciarTooltip"] = "Silenciar (M)",
        ["Player_Volumen"] = "Volumen",
        ["Player_Retroceder10Tooltip"] = "Retroceder 10s (←)",
        ["Player_Adelantar10Tooltip"] = "Adelantar 10s (→)",
        ["Player_Subtitulos"] = "Subtítulos",
        ["Player_MenuSubtitulos"] = "Menú de subtítulos",
        ["Player_ApagarSubtitulos"] = "Apagar",
        ["Player_PantallaCompletaTooltip"] = "Pantalla completa (F11)",
        ["Player_ModoFlotante"] = "Modo ventana flotante",
        ["Player_RestaurarFormatoNombre"] = "Restaurar formato habitual",

        // === CALENDARIO ===
        ["Cal_Titulo"] = "Calendario de Emisión",
        ["Cal_SinEpisodios"] = "Sin episodios",
        ["Cal_YaEmitidoTip"] = "Ya emitido",
        ["Cal_ProximoTip"] = "Próximo",
        ["Cal_AbrirFichaTip"] = "Abrir la ficha del anime",
        ["Cal_AbrirFichaAuto"] = "Ver {0} en la ficha",
        ["Cal_Hoy"] = "HOY",
        ["Cal_Lunes"] = "LUNES",
        ["Cal_Martes"] = "MARTES",
        ["Cal_Miercoles"] = "MIÉRCOLES",
        ["Cal_Jueves"] = "JUEVES",
        ["Cal_Viernes"] = "VIERNES",
        ["Cal_Sabado"] = "SÁBADO",
        ["Cal_Domingo"] = "DOMINGO",

        // === ACERCA DE ===
        ["Acerca_Titulo"] = "Acerca de AnimeLocalTracker",
        ["Acerca_Subtitulo"] = "Información del sistema, novedades de versiones y detalles del proyecto",
        ["Acerca_NombreApp"] = "AnimeLocalTracker",
        ["Acerca_Descripcion"] = "Gestor y reproductor nativo multimedia para colecciones de anime locales con sincronización inteligente en AniList.",
        ["Acerca_ComprobarActualizacionesTip"] = "Comprobar si hay una nueva versión disponible en GitHub",
        ["Acerca_BuscarActualizaciones"] = "Buscar Actualizaciones",
        ["Acerca_RegistroCambios"] = "Registro de cambios y mejoras publicadas",
        ["Acerca_ProyectoOpenSource"] = "Proyecto de Código Abierto (Open Source)",
        ["Acerca_Tecnologias"] = "Desarrollado con .NET 8, C#, WPF, Flyleaf, SQLite-net, MaterialDesign y Velopack.",
        ["Acerca_AbrirRepositorioTip"] = "Abrir repositorio en GitHub",
        ["Acerca_VerGitHub"] = "Ver en GitHub",
        ["Acerca_PrivacidadTitulo"] = "Privacidad y tus datos",
        ["Acerca_PrivacidadP1"] = "Local-first: tu biblioteca, historial de visionado, portadas y miniaturas se guardan SOLO en tu equipo (carpeta de datos de usuario de Windows) y nunca se suben.",
        ["Acerca_PrivacidadP2"] = "Al conectar AniList se lee tu perfil y lista, y se escribe en ella tu progreso, estado y puntuación cuando los marcas (consulta el aviso antes de conectar). AniSkip recibe solo identificadores públicos; las descargas no envían datos de tu cuenta.",
        ["Acerca_PrivacidadP3"] = "Sin telemetría ni analítica. Los registros (logs) y el historial se guardan en claro en tu equipo con retención acotada (log de 5 MB, 5 backups rotativos); desde Configuración puedes exportar tus datos o borrarlos todos.",
        ["Acerca_AvisoContenidoTitulo"] = "Aviso de contenido",
        ["Acerca_AvisoContenidoTexto"] = "AnimeLocalTracker es un catálogo y reproductor: no aloja ni distribuye ningún video. El catálogo de AniList que exploras aquí puede incluir series con clasificaciones de edad (violencia, contenido sexual sugerido u otros temas) no aptas para todo público; la app no verifica tu edad. Los archivos que reproduces son los que tú mismo añades a tu biblioteca local.",

        // === DESCARGAS ===
        ["Desc_Titulo"] = "Cola de descargas",
        ["Desc_GrupoEjemplo"] = "AnimeAv1",
        ["Desc_EnPausa"] = "En pausa",
        ["Desc_PausarReanudarTip"] = "Pausar o reanudar descarga",
        ["Desc_CancelarTip"] = "Cancelar descarga",
        ["Desc_VacioTitulo"] = "No hay descargas en curso",
        ["Desc_VacioSub"] = "Los capítulos que pongas a descargar se mostrarán aquí en tiempo real.",
        ["Desc_PausarTodas"] = "Pausar todas",
        ["Desc_ReanudarTodas"] = "Reanudar todas",
        ["Desc_MasOpcionesTip"] = "Más opciones",
        ["Desc_CancelarTodas"] = "Cancelar todas las descargas",

        // === CONFIGURACIÓN — borrar datos / plugins ===
        ["Cfg_BorrarDatosTitulo"] = "Borrar todos mis datos",
        ["Cfg_BorrarDatosSub"] = "Elimina biblioteca, historial, sesión de AniList, portadas, miniaturas, backups y logs locales. Tu lista en la nube NO se toca.",
        ["Cfg_BtnBorrarDatos"] = "Borrar datos",
        ["Cfg_BorrarDatosConfirmacionMsj"] = "Se eliminarán: tu biblioteca local (animes, historial de visionado y progreso), la sesión de AniList, las portadas, miniaturas, copias de seguridad y logs.\n\nTu lista en la nube de AniList NO se toca. Esta acción NO se puede deshacer.",
        ["Cfg_UltimaConfirmacionTitulo"] = "Última confirmación",
        ["Cfg_UltimaConfirmacionMsj"] = "¿Borrar TODOS tus datos locales ahora? La aplicación se cerrará y, al abrirla de nuevo, empezarás desde cero.",
        ["Cfg_Plugins"] = "Plugins y Extensiones",
        ["Cfg_PluginsSub"] = "Scrapers y herramientas de la comunidad (Python)",
        ["Cfg_SinPlugins"] = "No hay plugins instalados.",
        ["Cfg_AbrirCarpetaPlugins"] = "Abrir Carpeta",

        // === VENTANA PRINCIPAL — controles de ventana ===
        ["Win_Titulo"] = "Mi Biblioteca",
        ["Win_BtnPantallaCompleta"] = "Pantalla completa",
        ["Win_BtnMinimizar"] = "Minimizar",
        ["Win_BtnMaximizar"] = "Maximizar",
        ["Win_BtnCerrarApp"] = "Cerrar aplicación"
    };


    private static readonly Dictionary<string, string> En = new()
    {
        ["Nav_Galeria"] = "Library",
        ["Nav_Historial"] = "History",
        ["Nav_Actualizaciones"] = "Updates",
        ["Nav_Agregar"] = "Add Anime",
        ["Nav_Calendario"] = "Calendar",
        ["Nav_Descargas"] = "Downloads",
        ["Nav_Configuracion"] = "Settings",
        ["Nav_AcercaDe"] = "About",

        ["Cfg_Almacenamiento"] = "Storage",
        ["Cfg_AlmacenamientoSub"] = "Folder where your anime are stored and organized",
        ["Cfg_RutaHint"] = "Storage Path",
        ["Cfg_CambiarCarpeta"] = "Change Folder",
        ["Cfg_Explorador"] = "Explorer",
        ["Cfg_EspacioDisco"] = "Disk Space",
        ["Cfg_TotalAnimes"] = "registered anime",
        ["Cfg_LimpiarCache"] = "Clean image cache",
        ["Cfg_LimpiarCacheTip"] = "Removes thumbnails and covers of anime that no longer exist in your library",
        ["Cfg_ExportarBackup"] = "Export database backup",
        ["Cfg_BackupOk"] = "Backup created successfully.",
        ["Cfg_BackupError"] = "Could not create the backup.",
        ["Cfg_ExportarBiblioteca"] = "Export library (JSON)",
        ["Cfg_BibliotecaExportada"] = "Library exported: {0} anime and their history.",
        ["Cfg_ImportarBiblioteca"] = "Import library (JSON)",
        ["Cfg_ImportarConfirmacion"] = "The file's library will be merged with the current one (existing anime will be updated). Continue?",
        ["Cfg_BibliotecaImportada"] = "Library imported: {0} anime merged.",
        ["Cfg_BtnBackup"] = "Export backup",
        ["Cfg_BtnExportarJson"] = "Export library (JSON)",
        ["Cfg_BtnImportarJson"] = "Import library (JSON)",

        ["Cfg_Reproduccion"] = "Playback & Downloads",
        ["Cfg_ReproduccionSub"] = "Player behavior and concurrency settings",
        ["Cfg_AutoPlay"] = "Auto-play next episode",
        ["Cfg_AutoPlaySub"] = "Shows a 5s countdown and automatically plays the next chapter",
        ["Cfg_AutoSkip"] = "Auto-skip Intro / Outro (AniSkip)",
        ["Cfg_AutoSkipSub"] = "Skips openings and endings automatically without clicking",
        ["Cfg_Subtitulos"] = "Subtitles enabled by default",
        ["Cfg_SubtitulosSub"] = "Loads subtitle tracks automatically when starting a video",
        ["Cfg_DescargasSimultaneas"] = "Max simultaneous downloads",
        ["Cfg_DescargasSimultaneasSub"] = "Number of episodes downloading in parallel (1 to 5)",
        ["Cfg_IntervaloSync"] = "AniList sync interval",
        ["Cfg_IntervaloSyncSub"] = "Background frequency to sync your watch history",
        ["Cfg_Velocidad"] = "Default playback speed",
        ["Cfg_VelocidadSub"] = "Applied when opening each episode (adjustable in the player)",
        ["Cfg_Atajos"] = "Player keyboard shortcuts",
        ["Cfg_AtajosSub"] = "Customize hotkeys (applied when opening the player)",
        ["Atajo_PlayPausa"] = "Play / Pause",
        ["Atajo_PantallaCompleta"] = "Fullscreen",
        ["Atajo_Silenciar"] = "Mute",
        ["Atajo_SubirVolumen"] = "Volume up",
        ["Atajo_BajarVolumen"] = "Volume down",
        ["Atajo_Adelantar10"] = "Forward 10s",
        ["Atajo_Retroceder10"] = "Back 10s",
        ["Atajo_SaltarIntro"] = "Skip intro/outro",
        ["Atajo_SiguienteEpisodio"] = "Next episode",
        ["Atajo_AnteriorEpisodio"] = "Previous episode",
        ["Atajo_Cerrar"] = "Close player",
        ["Atajo_CapturarFrame"] = "Capture frame (screenshot)",
        ["Cfg_UmbralVisto"] = "Watched threshold",
        ["Cfg_UmbralVistoSub"] = "Percentage of the episode played from which it is automatically marked as watched",
        ["Cfg_NotificarEpisodios"] = "Notify new episodes",
        ["Cfg_NotificarEpisodiosSub"] = "Alerts when new episode files appear in your library",
        ["Cfg_Idioma"] = "Idioma / Language",
        ["Cfg_IdiomaSub"] = "The change applies instantly",
        ["Cfg_Guardar"] = "Save Preferences",

        ["Cfg_Cuenta"] = "AniList Account & Sync",
        ["Cfg_CuentaSub"] = "Link status to sync progress with your cloud profile",
        ["Cfg_SyncSub"] = "Episodes marked as watched sync automatically with your AniList online profile",
        ["Cfg_CerrarSesion"] = "Sign Out",

        ["Notif_NuevosEpisodios"] = "New episodes",
        ["Notif_ResumenNuevos"] = "new episode(s) detected in your library:",
        ["Notif_SinTitulo"] = "Anime",

        // === STATISTICS (LOC-01) ===
        ["Stats_Titulo"] = "Statistics Dashboard",
        ["Stats_Subtitulo"] = "Analysis of your watch history",
        ["Stats_EpisodiosVistos"] = "EPISODES WATCHED",
        ["Stats_HorasReproducidas"] = "HOURS PLAYED",
        ["Stats_AnimesBiblioteca"] = "ANIME IN LIBRARY",
        ["Stats_BibliotecaCompletada"] = "LIBRARY COMPLETED",
        ["Stats_AMedioVer"] = "In progress",
        ["Stats_EpisodiosFavoritos"] = "Favorite episodes",
        ["Stats_EpisodiosDescargados"] = "Downloaded episodes",
        ["Stats_DuracionPromedio"] = "Avg. duration / ep.",
        ["Stats_GeneroFavorito"] = "FAVORITE GENRE",
        ["Stats_AnimeMasVisto"] = "MOST WATCHED ANIME",
        ["Stats_AnioMasActivo"] = "MOST ACTIVE YEAR",
        ["Stats_Ritmo"] = "PACE",
        ["Stats_PorMes"] = " / month",
        ["Stats_RachaActual"] = "Current streak: ",
        ["Stats_DistribucionLista"] = "Your list distribution",
        ["Stats_PorEstado"] = "By tracking status",
        ["Stats_DonutCentroAnimes"] = "anime",
        ["Stats_AnalisisGenero"] = "Genre analysis",
        ["Stats_GeneroSub"] = "Anime with watched episodes, by genre",
        ["Stats_Actividad7Dias"] = "Activity of the last 7 days",
        ["Stats_PromedioDiarioSub"] = " episodes/day · max streak: ",
        ["Stats_TopAnimes"] = "Top 5 most watched anime",
        ["Stats_TopAnimesSub"] = "By number of episodes played",
        ["Stats_PorAnio"] = "Episodes watched per year",
        ["Stats_PorAnioSub"] = "Evolution of your yearly consumption",

        // === MAIN WINDOW (LOC-01) ===
        ["Nav_Estadisticas"] = "Statistics",
        ["Nav_ComprobarUpdates"] = "Check for updates on GitHub",
        ["Nav_PantallaCompleta"] = "Fullscreen (F11)",
        ["Dlg_Cancelar"] = "CANCEL",
        ["Dlg_Aceptar"] = "OK",

        // === DIÁLOGOS (LOC-04) ===
        ["Dlg_NuevaVersion"] = "New version available",
        ["Dlg_EncontroVersion"] = "Version {0} found. Do you want to download and install it now?",
        ["Dlg_AnimeExistente"] = "Anime Exists",
        ["Dlg_AnimeExistenteMsj"] = "The anime '{0}' is already in your library.",
        ["Dlg_AnimeAnadido"] = "Anime Added",
        ["Dlg_AnimeAnadidoMsj"] = "Folder automatically created at:\n{0}",
        ["Dlg_ErrorTitulo"] = "Error",
        ["Dlg_ErrorAnadirAnime"] = "Could not add the anime: {0}",
        ["Msg_NuevaVersion"] = "new version",
        ["Dlg_UpdatesModoDevTitulo"] = "Updates",
        ["Dlg_UpdatesModoDev"] = "You are in development mode ({0}). Automatic updates are enabled when compiling with the production installer.",
        ["Dlg_UpdatesAlDiaTitulo"] = "Up to date",
        ["Dlg_UpdatesAlDia"] = "You already have the latest version installed ({0}).",
        ["Dlg_UpdatesErrorConexionTitulo"] = "Connection Error",
        ["Dlg_UpdatesErrorConexion"] = "Could not reach the update server on GitHub. Check your internet connection.",
        ["Dlg_UpdatesListaTitulo"] = "Update ready",
        ["Dlg_UpdatesLista"] = "Version {0} has been downloaded and is ready to be applied.",

        // === SETTINGS (LOC-02) ===
        ["Cfg_CambiarCarpetaTip"] = "Choose a new storage folder",
        ["Cfg_ExploradorTip"] = "Open in Windows Explorer",
        ["Cfg_ColeccionTotal"] = "Total Collection",
        ["Tecla_Espacio"] = "Space",

        // === RESTORE BACKUP (BAK-03) ===
        ["Cfg_BtnRestaurar"] = "Restore backup",
        ["Cfg_RestaurarBackup"] = "Restore backup",
        ["Cfg_RestaurarConfirmacion"] = "The current library will be replaced by the selected backup. Continue?",
        ["Cfg_RestaurarOk"] = "Library restored successfully.",
        ["Cfg_RestaurarError"] = "Could not restore the backup (invalid or corrupt file).",

        // === HISTORIAL ===
        ["Hist_Titulo"] = "Watch History",
        ["Hist_Subtitulo"] = "Your in-progress and recently watched episodes",
        ["Hist_FiltroTodos"] = "All",
        ["Hist_FiltroEnProgreso"] = "In Progress",
        ["Hist_FiltroCompletados"] = "Completed",
        ["Hist_BuscarPlaceholder"] = "Search history...",
        ["Hist_LimpiarHistorial"] = "Clear history",
        ["Hist_LimpiarTitulo"] = "Clear all history?",
        ["Hist_LimpiarMensaje"] = "Playback dates and progress will be reset for all episodes. Your video files and library will remain unchanged.",
        ["Hist_Reanudar"] = "Resume",
        ["Hist_VerAnime"] = "View details",
        ["Hist_Quitar"] = "Remove from history",
        ["Hist_MarcarVisto"] = "Mark as watched",
        ["Hist_MarcarNoVisto"] = "Mark as unwatched",
        ["Hist_VacioTitulo"] = "Your history is empty",
        ["Hist_VacioSubtitulo"] = "Episodes you watch or leave in progress will appear here automatically.",
        ["Hist_ExplorarGaleria"] = "Explore library",
        ["Hist_SinResultados"] = "No episodes matched your search.",
        ["Hist_ArchivoNoEncontrado"] = "The video file no longer exists at the registered path.",
        ["Hist_FechaHoy"] = "Today",
        ["Hist_FechaAyer"] = "Yesterday",
        ["Hist_FechaSemana"] = "This week",
        ["Hist_FechaMes"] = "This month",
        ["Hist_FechaAnteriores"] = "Earlier",
        ["Hist_HaceMin"] = "{0} min ago",
        ["Hist_NoEnBiblioteca"] = "'{0}' is no longer in your local library. Add it from the + tab to watch or download it.",

        // === ACTUALIZACIONES ===
        ["Act_Titulo"] = "Updates",
        ["Act_Subtitulo"] = "Recently aired episodes of your ongoing anime",
        ["Act_Descargar"] = "Download",
        ["Act_Reproducir"] = "Play episode",
        ["Act_Descargado"] = "Downloaded",
        ["Act_EpisodioFormato"] = "Episode {0}",
        ["Act_BotonActualizar"] = "REFRESH",
        ["Act_VerAnime"] = "View anime details",
        ["Act_VacioTitulo"] = "No recent episodes",
        ["Act_VacioSub"] = "Here you'll see recently aired episodes from the past 7 days of the releasing anime in your library.",
        ["Act_HaceDias"] = "{0} days ago",

        // === SETTINGS TITLE (LOC-07) ===
        ["Cfg_Titulo"] = "Settings & Preferences",
        ["Cfg_TituloSub"] = "Customize your anime storage, playback and AniList sync",

        // === PIP / MINI PLAYER MODE ===
        ["Player_Pip"] = "Floating window mode (P)",
        ["Player_Mini"] = "Minimize to mini-player (P)",
        ["Player_RestaurarFormato"] = "Restore regular format (P)",
        ["Player_Cerrar"] = "Close player",
        ["Player_RestaurarPip"] = "Restore player",
        ["Pip_Banner_Reproduciendo"] = "Playing in floating window:",

        // === LIBRARY ===
        ["Gal_Titulo"] = "My Library",
        ["Gal_QueVerTip"] = "Pick the next unwatched episode of a random anime",
        ["Gal_QueVeoHoy"] = "WHAT TO WATCH",
        ["Gal_Buscando"] = "SEARCHING...",
        ["Gal_SeleccionMultiple"] = "Multi-select",
        ["Gal_ActualizarNube"] = "Refresh data from the cloud",
        ["Gal_ConectarTip"] = "Connect with AniList",
        ["Gal_Conectar"] = "CONNECT",
        ["Gal_CuentaSincronizadaTip"] = "Account synced with AniList (Click for options)",
        ["Gal_BuscarHint"] = "Search saved anime...",
        ["Gal_FiltrosTip"] = "Filter by genre, sorting and more",
        ["Gal_Filtros"] = "Filters",
        ["Gal_FiltroViendo"] = "Watching",
        ["Gal_FiltroPlaneando"] = "Planning",
        ["Gal_SoloPendientesTip"] = "Show only anime with pending unwatched episodes",
        ["Gal_Pendientes"] = "Pending",
        ["Gal_SoloCarpetaTip"] = "Show only anime with an assigned local folder",
        ["Gal_ConCarpetaLocal"] = "With local folder",
        ["Gal_LimpiarFiltrosTip"] = "Reset all filters and search",
        ["Gal_LimpiarFiltros"] = "Clear filters",
        ["Gal_MoverA"] = "Move to:",
        ["Gal_Cancelar"] = "Cancel",
        ["Gal_VacioTitulo"] = "Your library is empty",
        ["Gal_VacioSub"] = "Add an anime to start your local collection",
        ["Gal_BuscarYAnadir"] = "SEARCH AND ADD ANIME",
        ["Gal_SinResultadosTitulo"] = "No anime found",
        ["Gal_SinResultadosSub"] = "Try different search terms or change the status filter.",
        ["Gal_NuevosEpisodiosFormato"] = "{0} New",

        // === DETAIL ===
        ["Det_EnBibliotecaTip"] = "In your library (click to remove)",
        ["Det_Biblioteca"] = "Library",
        ["Det_SeguimientoTip"] = "Manage tracking and progress on AniList",
        ["Det_Seguimiento"] = "Tracking",
        ["Det_WebViewTip"] = "Open the official page in the web browser",
        ["Det_WebView"] = "WebView",
        ["Det_EpisodiosFormato"] = "{0} episodes",
        ["Det_OrdenTip"] = "Toggle ascending/descending order",
        ["Det_Carpeta"] = "Folder",
        ["Det_CarpetaTip"] = "Open the anime's folder in Explorer",
        ["Det_DetectarOpTip"] = "Analyze audio with the plugin to detect openings",
        ["Det_DetectarOp"] = "Detect OP",
        ["Det_MarcarVistosTip"] = "Mark selected episodes (or all) as watched",
        ["Det_Vistos"] = "Watched",
        ["Det_MarcarNoVistosTip"] = "Mark selected episodes (or all) as unwatched",
        ["Det_NoVistos"] = "Unwatched",
        ["Det_ActualizarTip"] = "Refresh info and episodes from AniList",
        ["Det_Actualizar"] = "Refresh",
        ["Det_DuplicadosTip"] = "Detect duplicate files by perceptual hash",
        ["Det_Duplicados"] = "Duplicates",
        ["Det_Analizando"] = "Analyzing...",
        ["Det_EliminarEpisodio"] = "Delete episode from disk",
        ["Det_FavoritoTip"] = "Mark as favorite / saved",
        ["Det_OpcionesTip"] = "Options (delete, etc.)",
        ["Det_OpcionesNombre"] = "Downloaded episode options",
        ["Det_DescargandoTip"] = "Downloading episode",
        ["Det_DescargarEpisodioTip"] = "Download episode",
        ["Det_ReanudarTip"] = "Continue playing the episode in progress",
        ["Det_ActualizarAniListTitulo"] = "Update on AniList",
        ["Det_ActualizarAniListSub"] = "Sync your progress and score with the cloud",
        ["Det_CerrarVentanaTip"] = "Close window",
        ["Det_Estado"] = "Status",
        ["Det_EpisodiosVistos"] = "Episodes Watched",
        ["Det_Puntuacion"] = "Score",
        ["Det_FechaInicio"] = "Start Date",
        ["Det_FechaFin"] = "End Date",
        ["Det_GuardarAniList"] = "Save to AniList",

        // === ADD ANIME ===
        ["Add_Titulo"] = "Add Anime",
        ["Add_Subtitulo"] = "Explore trending anime or search any title on AniList for your local collection",
        ["Add_BuscarHint"] = "Search by title (e.g. Frieren, Solo Leveling, Bleach)...",
        ["Add_LimpiarBusquedaTip"] = "Clear search",
        ["Add_Cargando"] = "Loading anime from AniList...",
        ["Add_SinResultadosTitulo"] = "No results found",
        ["Add_SinResultadosSub"] = "Try typing the title in Romaji, English, or with fewer keywords.",
        ["Add_VerTendencias"] = "View trending anime",
        ["Add_AnadirBibliotecaTip"] = "Add to my local library",
        ["Add_AnadirBiblioteca"] = "Add to library",
        ["Add_VerBibliotecaTip"] = "View details in your library",
        ["Add_EnBiblioteca"] = "In your library",

        // === PLAYER (tooltips) ===
        ["Player_VolverFicha"] = "Back to anime details",
        ["Player_SaltarSegmento"] = "Skip segment (Shortcut: S)",
        ["Player_ProgresoEpisodio"] = "Episode progress",
        ["Player_PlayPausaTooltip"] = "Play / Pause (Space)",
        ["Player_SilenciarToggle"] = "Mute or unmute",
        ["Player_SilenciarTooltip"] = "Mute (M)",
        ["Player_Volumen"] = "Volume",
        ["Player_Retroceder10Tooltip"] = "Back 10s (←)",
        ["Player_Adelantar10Tooltip"] = "Forward 10s (→)",
        ["Player_Subtitulos"] = "Subtitles",
        ["Player_MenuSubtitulos"] = "Subtitles menu",
        ["Player_ApagarSubtitulos"] = "Off",
        ["Player_PantallaCompletaTooltip"] = "Fullscreen (F11)",
        ["Player_ModoFlotante"] = "Floating window mode",
        ["Player_RestaurarFormatoNombre"] = "Restore regular format",

        // === CALENDAR ===
        ["Cal_Titulo"] = "Airing Calendar",
        ["Cal_SinEpisodios"] = "No episodes",
        ["Cal_YaEmitidoTip"] = "Already aired",
        ["Cal_ProximoTip"] = "Upcoming",
        ["Cal_AbrirFichaTip"] = "Open anime details",
        ["Cal_AbrirFichaAuto"] = "View {0} details",
        ["Cal_Hoy"] = "TODAY",
        ["Cal_Lunes"] = "MONDAY",
        ["Cal_Martes"] = "TUESDAY",
        ["Cal_Miercoles"] = "WEDNESDAY",
        ["Cal_Jueves"] = "THURSDAY",
        ["Cal_Viernes"] = "FRIDAY",
        ["Cal_Sabado"] = "SATURDAY",
        ["Cal_Domingo"] = "SUNDAY",

        // === ABOUT ===
        ["Acerca_Titulo"] = "About AnimeLocalTracker",
        ["Acerca_Subtitulo"] = "System information, version updates and project details",
        ["Acerca_NombreApp"] = "AnimeLocalTracker",
        ["Acerca_Descripcion"] = "Native media manager and player for local anime collections with smart AniList synchronization.",
        ["Acerca_ComprobarActualizacionesTip"] = "Check whether a new version is available on GitHub",
        ["Acerca_BuscarActualizaciones"] = "Check for Updates",
        ["Acerca_RegistroCambios"] = "Changelog of published fixes and improvements",
        ["Acerca_ProyectoOpenSource"] = "Open Source Project",
        ["Acerca_Tecnologias"] = "Built with .NET 8, C#, WPF, Flyleaf, SQLite-net, MaterialDesign and Velopack.",
        ["Acerca_AbrirRepositorioTip"] = "Open repository on GitHub",
        ["Acerca_VerGitHub"] = "View on GitHub",
        ["Acerca_PrivacidadTitulo"] = "Privacy and your data",
        ["Acerca_PrivacidadP1"] = "Local-first: your library, watch history, covers and thumbnails are stored ONLY on your machine (Windows user data folder) and are never uploaded.",
        ["Acerca_PrivacidadP2"] = "Connecting AniList reads your profile and list, and writes your progress, status and score to it when you mark them (check the notice before connecting). AniSkip only receives public identifiers; downloads do not send any account data.",
        ["Acerca_PrivacidadP3"] = "No telemetry or analytics. Logs and history are stored in plain text on your machine with limited retention (5 MB log, 5 rotating backups); you can export your data or delete it all from Settings.",
        ["Acerca_AvisoContenidoTitulo"] = "Content notice",
        ["Acerca_AvisoContenidoTexto"] = "AnimeLocalTracker is a catalog and player: it does not host or distribute any video. The AniList catalog you browse here may include series with age ratings (violence, suggestive sexual content or other themes) not suitable for all audiences; the app does not verify your age. The files you play are the ones you add to your local library yourself.",

        // === DOWNLOADS ===
        ["Desc_Titulo"] = "Download Queue",
        ["Desc_GrupoEjemplo"] = "AnimeAv1",
        ["Desc_EnPausa"] = "Paused",
        ["Desc_PausarReanudarTip"] = "Pause or resume download",
        ["Desc_CancelarTip"] = "Cancel download",
        ["Desc_VacioTitulo"] = "No downloads in progress",
        ["Desc_VacioSub"] = "Episodes you queue for download will appear here in real time.",
        ["Desc_PausarTodas"] = "Pause all",
        ["Desc_ReanudarTodas"] = "Resume all",
        ["Desc_MasOpcionesTip"] = "More options",
        ["Desc_CancelarTodas"] = "Cancel all downloads",

        // === SETTINGS — delete data / plugins ===
        ["Cfg_BorrarDatosTitulo"] = "Delete all my data",
        ["Cfg_BorrarDatosSub"] = "Deletes your library, history, AniList session, covers, thumbnails, backups and local logs. Your cloud list is NOT touched.",
        ["Cfg_BtnBorrarDatos"] = "Delete data",
        ["Cfg_BorrarDatosConfirmacionMsj"] = "This will delete: your local library (anime, watch history and progress), your AniList session, covers, thumbnails, backups and logs.\n\nYour AniList cloud list is NOT touched. This action CANNOT be undone.",
        ["Cfg_UltimaConfirmacionTitulo"] = "Final confirmation",
        ["Cfg_UltimaConfirmacionMsj"] = "Delete ALL your local data now? The application will close and, when you reopen it, you'll start from scratch.",
        ["Cfg_Plugins"] = "Plugins & Extensions",
        ["Cfg_PluginsSub"] = "Community scrapers and tools (Python)",
        ["Cfg_SinPlugins"] = "No plugins installed.",
        ["Cfg_AbrirCarpetaPlugins"] = "Open Folder",

        // === MAIN WINDOW — window controls ===
        ["Win_Titulo"] = "My Library",
        ["Win_BtnPantallaCompleta"] = "Fullscreen",
        ["Win_BtnMinimizar"] = "Minimize",
        ["Win_BtnMaximizar"] = "Maximize",
        ["Win_BtnCerrarApp"] = "Close application"
    };


    public string this[string key] =>
        _idioma == "en" && En.TryGetValue(key, out var en) ? en
        : Es.TryGetValue(key, out var es) ? es
        : key;

    /// <summary>Acceso desde código (C#): LocalizationService.T("Clave").</summary>
    public static string T(string key) => Instance[key];

    public event PropertyChangedEventHandler? PropertyChanged;

    private void OnPropertyChanged([CallerMemberName] string? nombre = null)
        => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nombre));
}
